use proc_macro2::TokenStream;
use quote::{ToTokens, quote};
use syn::parse2;

use crate::{
    character_classes::CharacterClasses, dfa::Dfa, nfa::Nfa, scanner_data::ScannerData,
    scanner_mode::ScannerMode,
};

/// This function generates the scanner code from the input token stream.
/// It parses the input token stream into a `ScannerData` struct and then generates the scanner
/// code.
/// It returns a `TokenStream` containing the generated code.
/// The input token stream is expected to contain the scanner definition, including the regex
/// patterns and actions.
/// The macro syntax is expected to be used in the following way:
/// ```ignore
/// use scnr_macro::scanner;
///
/// scanner! {
///     ExampleScanner {
///         mode INITIAL {
///             token r"\r\n|\r|\n" => 1;
///             token r"[\s--\r\n]+" => 2;
///             token r"//.*(\r\n|\r|\n)?" => 3;
///             token r"/\*([^*]|\*[^/])*\*/" => 4;
///             token r#"""# => 8;
///             token r"Hello" => 9;
///             token r"World" => 10;
///             token r"World" => 11 followed by r"!";
///             token r"!" => 12 not followed by r"!";
///             token r"[a-zA-Z_]\w*" => 13;
///             token r"." => 14;
///
///             transition 8 => STRING;
///         }
///         mode STRING {
///             token r#"\\[\"\\bfnt]"# => 5;
///             token r"\\[\s--\n\r]*\r?\n" => 6;
///             token r#"[^\"\]+"# => 7;
///             token r#"""# => 8;
///             token r"." => 14;
///
///             transition 8 => INITIAL;
//          }
///     }
/// }
/// ```
/// where there must be at least one scanner mode with at least one `token` entry.
/// A `token` entry is a regex pattern followed by an arrow and a token type number.
/// Optional `not` and `followed by` modifiers can be used to specify positive and negative
/// lookaheads.
/// Zero or more `transition` entries can exist.
/// The `transition` entries are tuples of the token type numbers and the new scanner mode name.
///
/// The generated code will include the scanner implementation.
/// The generated scanner in this example will be a struct named `ExampleScanner` which implements
/// the `ScannerTrait`.
pub fn generate(input: TokenStream) -> TokenStream {
    let scanner_data: ScannerData = parse2(input).expect("Failed to parse input");
    let scanner_modes: Vec<ScannerMode> = scanner_data
        .build_scanner_modes()
        .expect("Failed to build scanner modes");

    // Generate NFAs for each scanner mode
    let mut nfas = scanner_modes
        .iter()
        .map(|mode| {
            // Build the NFA for each pattern in the scanner mode
            Nfa::build_from_patterns(&mode.patterns).expect("Failed to build NFA for pattern")
        })
        .collect::<Vec<_>>();

    let mut character_classes = CharacterClasses::new();
    // For each NFA, generate the character classes
    for nfa in &nfas {
        nfa.collect_character_classes(&mut character_classes)
    }
    // Generate disjoint character classes
    character_classes.create_disjoint_character_classes();
    // Convert the NFA to use disjoint character classes
    for nfa in &mut nfas {
        nfa.convert_to_disjoint_character_classes(&character_classes);
    }

    // Convert the nfas into DFAs
    let dfas = nfas
        .into_iter()
        .try_fold(Vec::new(), |mut acc, nfa| -> Result<Vec<Dfa>, syn::Error> {
            // Convert the NFA to a DFA
            let dfa = Dfa::try_from(&nfa).map_err(|e| {
                syn::Error::new(
                    proc_macro2::Span::call_site(),
                    format!("Failed to convert NFA to DFA: {}", e),
                )
            })?;
            // Add the DFA to the accumulator
            acc.push(dfa);
            Ok(acc)
        })
        .expect("Failed to convert NFAs to DFAs");

    // TODO: Remove this debug assertion later when the dfa variable is actually used
    // Used only to ensure that compiler doesn't optimize the variable dfa away
    debug_assert_eq!(
        dfas.len(),
        scanner_modes.len(),
        "The number of DFAs should match the number of scanner modes"
    );

    // Convert the scanner name to snake case for the module name
    let module_name = to_snake_case(&scanner_data.name);
    let module_name_ident = syn::Ident::new(&module_name, proc_macro2::Span::call_site());

    // Make the scanner name an syn::Ident
    let scanner_name = syn::Ident::new(&scanner_data.name, proc_macro2::Span::call_site());
    let match_function_code = character_classes.generate("match_function");

    let modes = scanner_modes.into_iter().enumerate().map(|(index, mode)| {
        let mode_name = syn::Ident::new(&mode.name, proc_macro2::Span::call_site());
        let transitions = mode.transitions.iter().map(|(token_type, new_mode_index)| {
            quote! {
                (#token_type, #new_mode_index)
            }
        });
        let states = dfas.get(index).map_or_else(
            || panic!("DFA for mode {} not found", mode.name),
            |dfa| {
                dfa.states.iter().map(|state| {
                    let transitions = state.transitions.iter().map(|t| t.to_token_stream());
                    let accept_data = state.accept_data.as_ref().map_or_else(
                        || quote! { None },
                        |ad| {
                            quote! {
                                Some(AcceptData {
                                    token_type: #ad.token_type,
                                    lookahead: #ad.lookahead
                                })
                            }
                        },
                    );
                    quote! {
                        DfaState {
                            transitions: vec![#(#transitions),*],
                            accept_data: #accept_data
                        }
                    }
                })
            },
        );
        quote! {
            ScannerMode {
                name: stringify!(#mode_name).to_string(),
                transitions: vec![#(#transitions),*],
                dfa: Dfa { states: vec![#(#states),*] }
            }
        }
    });

    let output = quote! {
        mod #module_name_ident {
            struct ScannerMode {
                name: std::string::String,
                transitions: std::vec::Vec<(usize, usize)>,
                dfa: Dfa
            }
            struct Dfa {
                states: std::vec::Vec<DfaState>
            }
            struct DfaState {
                transitions: std::vec::Vec<DfaTransition>,
                accept_data: std::option::Option<AcceptData>
            }
            struct AcceptData {
                token_type: usize,
                lookahead: Lookahead
            }
            enum Lookahead {
                None,
                Positive(Dfa),
                Negative(Dfa)
            }
            struct DfaTransition {
                char_class: usize,
                to: usize
            }
            pub struct #scanner_name {
                modes: std::vec::Vec<ScannerMode>,
                current_mode: usize,
            }
            impl #scanner_name {
                pub fn new() -> Self {
                    #scanner_name {
                        modes: vec![
                            #(
                                #modes
                            )*
                        ],
                        current_mode: 0,
                    }
                }
                #match_function_code
            }
        }
    };

    output
}

/// Converts a string from PascalCase or camelCase to snake_case
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    let chars = s.chars().peekable();

    for c in chars {
        if c.is_uppercase() {
            // Add underscore if not at the beginning and not after an underscore
            if !result.is_empty() && !result.ends_with('_') {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use std::io::Write;

    use super::*;

    use crate::Result;
    use std::path::Path;

    use std::process::Command;

    /// Tries to format the source code of a given file.
    fn try_format(path_to_file: &Path) -> Result<()> {
        Command::new("rustfmt")
            .args([path_to_file])
            .status()
            .map(|_| ())
            .map_err(|e| {
                std::io::Error::new(e.kind(), format!("Failed to format file: {}", e)).into()
            })
    }

    #[test]
    fn test_generate() {
        let input = quote::quote! {
            HelloWorld {
                mode INITIAL {
                    token r"\r\n|\r|\n" => 1;
                    token r"[\s--\r\n]+" => 2;
                    token r"//.*(\r\n|\r|\n)?" => 3;
                    token r"/\*([^*]|\*[^/])*\*/" => 4;
                    token r#"""# => 8;
                    token r"Hello" => 9;
                    token r"World" => 10;
                    token r"World" => 11 followed by r"!";
                    token r"!" => 12 not followed by r"!";
                    token r"[a-zA-Z_]\w*" => 13;
                    token r"." => 14;

                    transition 8 => STRING;
                }
                mode STRING {
                    token r#"\\[\"\\bfnt]"# => 5;
                    token r"\\[\s--\r\n]*\r?\n" => 6;
                    token r#"[^\"\\]+"# => 7;
                    token r#"""# => 8;
                    token r"." => 14;

                    transition 8 => INITIAL;
                }
            }
        };
        let code = generate(input).to_string();

        // Create a temporary file
        let mut temp_file =
            tempfile::NamedTempFile::new().expect("Failed to create temporary file");

        // Write the generated code to the temporary file
        temp_file
            .write_all(code.as_bytes())
            .expect("Failed to write to temporary file");

        // Optionally, print the file path for debugging
        println!("Temporary file created at: {:?}", temp_file.path());

        // Format the file (if needed)
        try_format(temp_file.path()).expect("Failed to format the temporary file");

        // Load the formatted code and convert possible \r\n to \n for easier comparison
        let formatted_code = std::fs::read_to_string(temp_file.path())
            .expect("Failed to read the formatted temporary file")
            .replace("\r\n", "\n");

        let expected_code = r#"struct HelloWorld {}
impl HelloWorld {
    fn new() -> Self {
        HelloWorld {}
    }
    #[allow(clippy::manual_is_ascii_check, dead_code)]
    pub(crate) fn match_function(c: char) -> Option<usize> {
        use std::cmp::Ordering;
        static GROUPED_INTERVALS: &[&[std::ops::RangeInclusive<char>]] = &[
            &[
                '\0'..='\u{8}',
                '\u{e}'..='\u{1f}',
                '#'..=')',
                '+'..='.',
                ':'..='@',
                '['..='[',
                ']'..='^',
                '`'..='`',
                '{'..='\u{84}',
                '\u{86}'..='\u{9f}',
                '¡'..='©',
                '«'..='´',
                '¶'..='¹',
                '»'..='¿',
                '×'..='×',
                '÷'..='÷',
                '˂'..='˅',
                '˒'..='˟',
                '˥'..='˫',
                '˭'..='˭',
                '˯'..='˿',
                '͵'..='͵',
                '\u{378}'..='\u{379}',
                ';'..=';',
                '\u{380}'..='΅',
                '·'..='·',
                '\u{38b}'..='\u{38b}',
                '\u{38d}'..='\u{38d}',
                '\u{3a2}'..='\u{3a2}',
                '϶'..='϶',
                '҂'..='҂',
                '\u{530}'..='\u{530}',
                '\u{557}'..='\u{558}',
                '՚'..='՟',
                '։'..='\u{590}',
                '־'..='־',
                '׀'..='׀',
                '׃'..='׃',
                '׆'..='׆',
                '\u{5c8}'..='\u{5cf}',
                '\u{5eb}'..='\u{5ee}',
                '׳'..='؏',
                '؛'..='؟',
                '٪'..='٭',
                '۔'..='۔',
                '\u{6dd}'..='۞',
                '۩'..='۩',
                '۽'..='۾',
                '܀'..='\u{70f}',
                '\u{74b}'..='\u{74c}',
                '\u{7b2}'..='\u{7bf}',
                '߶'..='߹',
                '\u{7fb}'..='\u{7fc}',
                '߾'..='߿',
                '\u{82e}'..='\u{83f}',
                '\u{85c}'..='\u{85f}',
                '\u{86b}'..='\u{86f}',
                '࢈'..='࢈',
                '\u{88f}'..='\u{896}',
                '\u{8e2}'..='\u{8e2}',
                '।'..='॥',
                '॰'..='॰',
                '\u{984}'..='\u{984}',
                '\u{98d}'..='\u{98e}',
                '\u{991}'..='\u{992}',
                '\u{9a9}'..='\u{9a9}',
                '\u{9b1}'..='\u{9b1}',
                '\u{9b3}'..='\u{9b5}',
                '\u{9ba}'..='\u{9bb}',
                '\u{9c5}'..='\u{9c6}',
                '\u{9c9}'..='\u{9ca}',
                '\u{9cf}'..='\u{9d6}',
                '\u{9d8}'..='\u{9db}',
                '\u{9de}'..='\u{9de}',
                '\u{9e4}'..='\u{9e5}',
                '৲'..='৻',
                '৽'..='৽',
                '\u{9ff}'..='\u{a00}',
                '\u{a04}'..='\u{a04}',
                '\u{a0b}'..='\u{a0e}',
                '\u{a11}'..='\u{a12}',
                '\u{a29}'..='\u{a29}',
                '\u{a31}'..='\u{a31}',
                '\u{a34}'..='\u{a34}',
                '\u{a37}'..='\u{a37}',
                '\u{a3a}'..='\u{a3b}',
                '\u{a3d}'..='\u{a3d}',
                '\u{a43}'..='\u{a46}',
                '\u{a49}'..='\u{a4a}',
                '\u{a4e}'..='\u{a50}',
                '\u{a52}'..='\u{a58}',
                '\u{a5d}'..='\u{a5d}',
                '\u{a5f}'..='\u{a65}',
                '੶'..='\u{a80}',
                '\u{a84}'..='\u{a84}',
                '\u{a8e}'..='\u{a8e}',
                '\u{a92}'..='\u{a92}',
                '\u{aa9}'..='\u{aa9}',
                '\u{ab1}'..='\u{ab1}',
                '\u{ab4}'..='\u{ab4}',
                '\u{aba}'..='\u{abb}',
                '\u{ac6}'..='\u{ac6}',
                '\u{aca}'..='\u{aca}',
                '\u{ace}'..='\u{acf}',
                '\u{ad1}'..='\u{adf}',
                '\u{ae4}'..='\u{ae5}',
                '૰'..='\u{af8}',
                '\u{b00}'..='\u{b00}',
                '\u{b04}'..='\u{b04}',
                '\u{b0d}'..='\u{b0e}',
                '\u{b11}'..='\u{b12}',
                '\u{b29}'..='\u{b29}',
                '\u{b31}'..='\u{b31}',
                '\u{b34}'..='\u{b34}',
                '\u{b3a}'..='\u{b3b}',
                '\u{b45}'..='\u{b46}',
                '\u{b49}'..='\u{b4a}',
                '\u{b4e}'..='\u{b54}',
                '\u{b58}'..='\u{b5b}',
                '\u{b5e}'..='\u{b5e}',
                '\u{b64}'..='\u{b65}',
                '୰'..='୰',
                '୲'..='\u{b81}',
                '\u{b84}'..='\u{b84}',
                '\u{b8b}'..='\u{b8d}',
                '\u{b91}'..='\u{b91}',
                '\u{b96}'..='\u{b98}',
                '\u{b9b}'..='\u{b9b}',
                '\u{b9d}'..='\u{b9d}',
                '\u{ba0}'..='\u{ba2}',
                '\u{ba5}'..='\u{ba7}',
                '\u{bab}'..='\u{bad}',
                '\u{bba}'..='\u{bbd}',
                '\u{bc3}'..='\u{bc5}',
                '\u{bc9}'..='\u{bc9}',
                '\u{bce}'..='\u{bcf}',
                '\u{bd1}'..='\u{bd6}',
                '\u{bd8}'..='\u{be5}',
                '௰'..='\u{bff}',
                '\u{c0d}'..='\u{c0d}',
                '\u{c11}'..='\u{c11}',
                '\u{c29}'..='\u{c29}',
                '\u{c3a}'..='\u{c3b}',
                '\u{c45}'..='\u{c45}',
                '\u{c49}'..='\u{c49}',
                '\u{c4e}'..='\u{c54}',
                '\u{c57}'..='\u{c57}',
                '\u{c5b}'..='\u{c5c}',
                '\u{c5e}'..='\u{c5f}',
                '\u{c64}'..='\u{c65}',
                '\u{c70}'..='౿',
                '಄'..='಄',
                '\u{c8d}'..='\u{c8d}',
                '\u{c91}'..='\u{c91}',
                '\u{ca9}'..='\u{ca9}',
                '\u{cb4}'..='\u{cb4}',
                '\u{cba}'..='\u{cbb}',
                '\u{cc5}'..='\u{cc5}',
                '\u{cc9}'..='\u{cc9}',
                '\u{cce}'..='\u{cd4}',
                '\u{cd7}'..='\u{cdc}',
                '\u{cdf}'..='\u{cdf}',
                '\u{ce4}'..='\u{ce5}',
                '\u{cf0}'..='\u{cf0}',
                '\u{cf4}'..='\u{cff}',
                '\u{d0d}'..='\u{d0d}',
                '\u{d11}'..='\u{d11}',
                '\u{d45}'..='\u{d45}',
                '\u{d49}'..='\u{d49}',
                '൏'..='\u{d53}',
                '൘'..='൞',
                '\u{d64}'..='\u{d65}',
                '൰'..='൹',
                '\u{d80}'..='\u{d80}',
                '\u{d84}'..='\u{d84}',
                '\u{d97}'..='\u{d99}',
                '\u{db2}'..='\u{db2}',
                '\u{dbc}'..='\u{dbc}',
                '\u{dbe}'..='\u{dbf}',
                '\u{dc7}'..='\u{dc9}',
                '\u{dcb}'..='\u{dce}',
                '\u{dd5}'..='\u{dd5}',
                '\u{dd7}'..='\u{dd7}',
                '\u{de0}'..='\u{de5}',
                '\u{df0}'..='\u{df1}',
                '෴'..='\u{e00}',
                '\u{e3b}'..='฿',
                '๏'..='๏',
                '๚'..='\u{e80}',
                '\u{e83}'..='\u{e83}',
                '\u{e85}'..='\u{e85}',
                '\u{e8b}'..='\u{e8b}',
                '\u{ea4}'..='\u{ea4}',
                '\u{ea6}'..='\u{ea6}',
                '\u{ebe}'..='\u{ebf}',
                '\u{ec5}'..='\u{ec5}',
                '\u{ec7}'..='\u{ec7}',
                '\u{ecf}'..='\u{ecf}',
                '\u{eda}'..='\u{edb}',
                '\u{ee0}'..='\u{eff}',
                '༁'..='༗',
                '༚'..='༟',
                '༪'..='༴',
                '༶'..='༶',
                '༸'..='༸',
                '༺'..='༽',
                '\u{f48}'..='\u{f48}',
                '\u{f6d}'..='\u{f70}',
                '྅'..='྅',
                '\u{f98}'..='\u{f98}',
                '\u{fbd}'..='࿅',
                '࿇'..='\u{fff}',
                '၊'..='၏',
                '႞'..='႟',
                '\u{10c6}'..='\u{10c6}',
                '\u{10c8}'..='\u{10cc}',
                '\u{10ce}'..='\u{10cf}',
                '჻'..='჻',
                '\u{1249}'..='\u{1249}',
                '\u{124e}'..='\u{124f}',
                '\u{1257}'..='\u{1257}',
                '\u{1259}'..='\u{1259}',
                '\u{125e}'..='\u{125f}',
                '\u{1289}'..='\u{1289}',
                '\u{128e}'..='\u{128f}',
                '\u{12b1}'..='\u{12b1}',
                '\u{12b6}'..='\u{12b7}',
                '\u{12bf}'..='\u{12bf}',
                '\u{12c1}'..='\u{12c1}',
                '\u{12c6}'..='\u{12c7}',
                '\u{12d7}'..='\u{12d7}',
                '\u{1311}'..='\u{1311}',
                '\u{1316}'..='\u{1317}',
                '\u{135b}'..='\u{135c}',
                '፠'..='\u{137f}',
                '᎐'..='\u{139f}',
                '\u{13f6}'..='\u{13f7}',
                '\u{13fe}'..='᐀',
                '᙭'..='᙮',
                '᚛'..='\u{169f}',
                '᛫'..='᛭',
                '\u{16f9}'..='\u{16ff}',
                '\u{1716}'..='\u{171e}',
                '᜵'..='\u{173f}',
                '\u{1754}'..='\u{175f}',
                '\u{176d}'..='\u{176d}',
                '\u{1771}'..='\u{1771}',
                '\u{1774}'..='\u{177f}',
                '។'..='៖',
                '៘'..='៛',
                '\u{17de}'..='\u{17df}',
                '\u{17ea}'..='᠊',
                '\u{180e}'..='\u{180e}',
                '\u{181a}'..='\u{181f}',
                '\u{1879}'..='\u{187f}',
                '\u{18ab}'..='\u{18af}',
                '\u{18f6}'..='\u{18ff}',
                '\u{191f}'..='\u{191f}',
                '\u{192c}'..='\u{192f}',
                '\u{193c}'..='᥅',
                '\u{196e}'..='\u{196f}',
                '\u{1975}'..='\u{197f}',
                '\u{19ac}'..='\u{19af}',
                '\u{19ca}'..='\u{19cf}',
                '᧚'..='᧿',
                '\u{1a1c}'..='᨟',
                '\u{1a5f}'..='\u{1a5f}',
                '\u{1a7d}'..='\u{1a7e}',
                '\u{1a8a}'..='\u{1a8f}',
                '\u{1a9a}'..='᪦',
                '᪨'..='\u{1aaf}',
                '\u{1acf}'..='\u{1aff}',
                '\u{1b4d}'..='᭏',
                '᭚'..='᭪',
                '᭴'..='᭿',
                '\u{1bf4}'..='᯿',
                '\u{1c38}'..='᰿',
                '\u{1c4a}'..='\u{1c4c}',
                '᱾'..='᱿',
                '\u{1c8b}'..='\u{1c8f}',
                '\u{1cbb}'..='\u{1cbc}',
                '᳀'..='\u{1ccf}',
                '᳓'..='᳓',
                '\u{1cfb}'..='\u{1cff}',
                '\u{1f16}'..='\u{1f17}',
                '\u{1f1e}'..='\u{1f1f}',
                '\u{1f46}'..='\u{1f47}',
                '\u{1f4e}'..='\u{1f4f}',
                '\u{1f58}'..='\u{1f58}',
                '\u{1f5a}'..='\u{1f5a}',
                '\u{1f5c}'..='\u{1f5c}',
                '\u{1f5e}'..='\u{1f5e}',
                '\u{1f7e}'..='\u{1f7f}',
                '\u{1fb5}'..='\u{1fb5}',
                '᾽'..='᾽',
                '᾿'..='῁',
                '\u{1fc5}'..='\u{1fc5}',
                '῍'..='῏',
                '\u{1fd4}'..='\u{1fd5}',
                '\u{1fdc}'..='῟',
                '῭'..='\u{1ff1}',
                '\u{1ff5}'..='\u{1ff5}',
                '´'..='\u{1fff}',
                '\u{200b}'..='\u{200b}',
                '\u{200e}'..='‧',
                '\u{202a}'..='\u{202e}',
                '‰'..='‾',
                '⁁'..='⁓',
                '⁕'..='⁞',
                '\u{2060}'..='⁰',
                '\u{2072}'..='⁾',
                '₀'..='\u{208f}',
                '\u{209d}'..='\u{20cf}',
                '\u{20f1}'..='℁',
                '℃'..='℆',
                '℈'..='℉',
                '℔'..='℔',
                '№'..='℘',
                '℞'..='℣',
                '℥'..='℥',
                '℧'..='℧',
                '℩'..='℩',
                '℮'..='℮',
                '℺'..='℻',
                '⅀'..='⅄',
                '⅊'..='⅍',
                '⅏'..='⅟',
                '↉'..='⒵',
                '⓪'..='⯿',
                '⳥'..='⳪',
                '\u{2cf4}'..='⳿',
                '\u{2d26}'..='\u{2d26}',
                '\u{2d28}'..='\u{2d2c}',
                '\u{2d2e}'..='\u{2d2f}',
                '\u{2d68}'..='\u{2d6e}',
                '⵰'..='\u{2d7e}',
                '\u{2d97}'..='\u{2d9f}',
                '\u{2da7}'..='\u{2da7}',
                '\u{2daf}'..='\u{2daf}',
                '\u{2db7}'..='\u{2db7}',
                '\u{2dbf}'..='\u{2dbf}',
                '\u{2dc7}'..='\u{2dc7}',
                '\u{2dcf}'..='\u{2dcf}',
                '\u{2dd7}'..='\u{2dd7}',
                '\u{2ddf}'..='\u{2ddf}',
                '⸀'..='⸮',
                '⸰'..='⿿',
                '、'..='〄',
                '〈'..='〠',
                '〰'..='〰',
                '〶'..='〷',
                '〽'..='\u{3040}',
                '\u{3097}'..='\u{3098}',
                '゛'..='゜',
                '゠'..='゠',
                '・'..='・',
                '\u{3100}'..='\u{3104}',
                '\u{3130}'..='\u{3130}',
                '\u{318f}'..='㆟',
                '㇀'..='㇯',
                '㈀'..='㏿',
                '䷀'..='䷿',
                '\u{a48d}'..='\u{a4cf}',
                '꓾'..='꓿',
                '꘍'..='꘏',
                '\u{a62c}'..='\u{a63f}',
                '꙳'..='꙳',
                '꙾'..='꙾',
                '꛲'..='꜖',
                '꜠'..='꜡',
                '꞉'..='꞊',
                '\u{a7ce}'..='\u{a7cf}',
                '\u{a7d2}'..='\u{a7d2}',
                '\u{a7d4}'..='\u{a7d4}',
                '\u{a7dd}'..='\u{a7f1}',
                '꠨'..='꠫',
                '\u{a82d}'..='\u{a83f}',
                '꡴'..='\u{a87f}',
                '\u{a8c6}'..='꣏',
                '\u{a8da}'..='\u{a8df}',
                '꣸'..='꣺',
                '꣼'..='꣼',
                '꤮'..='꤯',
                '\u{a954}'..='꥟',
                '\u{a97d}'..='\u{a97f}',
                '꧁'..='\u{a9ce}',
                '\u{a9da}'..='꧟',
                '\u{a9ff}'..='\u{a9ff}',
                '\u{aa37}'..='\u{aa3f}',
                '\u{aa4e}'..='\u{aa4f}',
                '\u{aa5a}'..='꩟',
                '꩷'..='꩹',
                '\u{aac3}'..='\u{aada}',
                '꫞'..='꫟',
                '꫰'..='꫱',
                '\u{aaf7}'..='\u{ab00}',
                '\u{ab07}'..='\u{ab08}',
                '\u{ab0f}'..='\u{ab10}',
                '\u{ab17}'..='\u{ab1f}',
                '\u{ab27}'..='\u{ab27}',
                '\u{ab2f}'..='\u{ab2f}',
                '꭛'..='꭛',
                '꭪'..='\u{ab6f}',
                '꯫'..='꯫',
                '\u{abee}'..='\u{abef}',
                '\u{abfa}'..='\u{abff}',
                '\u{d7a4}'..='\u{d7af}',
                '\u{d7c7}'..='\u{d7ca}',
                '\u{d7fc}'..='\u{f8ff}',
                '\u{fa6e}'..='\u{fa6f}',
                '\u{fada}'..='\u{faff}',
                '\u{fb07}'..='\u{fb12}',
                '\u{fb18}'..='\u{fb1c}',
                '﬩'..='﬩',
                '\u{fb37}'..='\u{fb37}',
                '\u{fb3d}'..='\u{fb3d}',
                '\u{fb3f}'..='\u{fb3f}',
                '\u{fb42}'..='\u{fb42}',
                '\u{fb45}'..='\u{fb45}',
                '﮲'..='\u{fbd2}',
                '﴾'..='﵏',
                '\u{fd90}'..='\u{fd91}',
                '\u{fdc8}'..='\u{fdef}',
                '﷼'..='﷿',
                '︐'..='\u{fe1f}',
                '︰'..='︲',
                '︵'..='﹌',
                '﹐'..='\u{fe6f}',
                '\u{fe75}'..='\u{fe75}',
                '\u{fefd}'..='／',
                '：'..='＠',
                '［'..='＾',
                '｀'..='｀',
                '｛'..='･',
                '\u{ffbf}'..='\u{ffc1}',
                '\u{ffc8}'..='\u{ffc9}',
                '\u{ffd0}'..='\u{ffd1}',
                '\u{ffd8}'..='\u{ffd9}',
                '\u{ffdd}'..='\u{ffff}',
                '\u{1000c}'..='\u{1000c}',
                '\u{10027}'..='\u{10027}',
                '\u{1003b}'..='\u{1003b}',
                '\u{1003e}'..='\u{1003e}',
                '\u{1004e}'..='\u{1004f}',
                '\u{1005e}'..='\u{1007f}',
                '\u{100fb}'..='𐄿',
                '𐅵'..='𐇼',
                '\u{101fe}'..='\u{1027f}',
                '\u{1029d}'..='\u{1029f}',
                '\u{102d1}'..='\u{102df}',
                '𐋡'..='\u{102ff}',
                '𐌠'..='\u{1032c}',
                '\u{1034b}'..='\u{1034f}',
                '\u{1037b}'..='\u{1037f}',
                '\u{1039e}'..='𐎟',
                '\u{103c4}'..='\u{103c7}',
                '𐏐'..='𐏐',
                '\u{103d6}'..='\u{103ff}',
                '\u{1049e}'..='\u{1049f}',
                '\u{104aa}'..='\u{104af}',
                '\u{104d4}'..='\u{104d7}',
                '\u{104fc}'..='\u{104ff}',
                '\u{10528}'..='\u{1052f}',
                '\u{10564}'..='𐕯',
                '\u{1057b}'..='\u{1057b}',
                '\u{1058b}'..='\u{1058b}',
                '\u{10593}'..='\u{10593}',
                '\u{10596}'..='\u{10596}',
                '\u{105a2}'..='\u{105a2}',
                '\u{105b2}'..='\u{105b2}',
                '\u{105ba}'..='\u{105ba}',
                '\u{105bd}'..='\u{105bf}',
                '\u{105f4}'..='\u{105ff}',
                '\u{10737}'..='\u{1073f}',
                '\u{10756}'..='\u{1075f}',
                '\u{10768}'..='\u{1077f}',
                '\u{10786}'..='\u{10786}',
                '\u{107b1}'..='\u{107b1}',
                '\u{107bb}'..='\u{107ff}',
                '\u{10806}'..='\u{10807}',
                '\u{10809}'..='\u{10809}',
                '\u{10836}'..='\u{10836}',
                '\u{10839}'..='\u{1083b}',
                '\u{1083d}'..='\u{1083e}',
                '\u{10856}'..='𐡟',
                '𐡷'..='𐡿',
                '\u{1089f}'..='\u{108df}',
                '\u{108f3}'..='\u{108f3}',
                '\u{108f6}'..='𐣿',
                '𐤖'..='𐤟',
                '\u{1093a}'..='\u{1097f}',
                '\u{109b8}'..='𐦽',
                '𐧀'..='𐧿',
                '\u{10a04}'..='\u{10a04}',
                '\u{10a07}'..='\u{10a0b}',
                '\u{10a14}'..='\u{10a14}',
                '\u{10a18}'..='\u{10a18}',
                '\u{10a36}'..='\u{10a37}',
                '\u{10a3b}'..='\u{10a3e}',
                '𐩀'..='\u{10a5f}',
                '𐩽'..='𐩿',
                '𐪝'..='\u{10abf}',
                '𐫈'..='𐫈',
                '\u{10ae7}'..='\u{10aff}',
                '\u{10b36}'..='𐬿',
                '\u{10b56}'..='𐭟',
                '\u{10b73}'..='𐭿',
                '\u{10b92}'..='\u{10bff}',
                '\u{10c49}'..='\u{10c7f}',
                '\u{10cb3}'..='\u{10cbf}',
                '\u{10cf3}'..='𐳿',
                '\u{10d28}'..='\u{10d2f}',
                '\u{10d3a}'..='\u{10d3f}',
                '\u{10d66}'..='\u{10d68}',
                '𐵮'..='𐵮',
                '\u{10d86}'..='\u{10e7f}',
                '\u{10eaa}'..='\u{10eaa}',
                '𐺭'..='\u{10eaf}',
                '\u{10eb2}'..='\u{10ec1}',
                '\u{10ec5}'..='\u{10efb}',
                '𐼝'..='𐼦',
                '\u{10f28}'..='\u{10f2f}',
                '𐽑'..='\u{10f6f}',
                '𐾆'..='\u{10faf}',
                '𐿅'..='\u{10fdf}',
                '\u{10ff7}'..='\u{10fff}',
                '𑁇'..='𑁥',
                '\u{11076}'..='\u{1107e}',
                '𑂻'..='𑃁',
                '\u{110c3}'..='\u{110cf}',
                '\u{110e9}'..='\u{110ef}',
                '\u{110fa}'..='\u{110ff}',
                '\u{11135}'..='\u{11135}',
                '𑅀'..='𑅃',
                '\u{11148}'..='\u{1114f}',
                '𑅴'..='𑅵',
                '\u{11177}'..='\u{1117f}',
                '𑇅'..='𑇈',
                '𑇍'..='𑇍',
                '𑇛'..='𑇛',
                '𑇝'..='\u{111ff}',
                '\u{11212}'..='\u{11212}',
                '𑈸'..='𑈽',
                '\u{11242}'..='\u{1127f}',
                '\u{11287}'..='\u{11287}',
                '\u{11289}'..='\u{11289}',
                '\u{1128e}'..='\u{1128e}',
                '\u{1129e}'..='\u{1129e}',
                '𑊩'..='\u{112af}',
                '\u{112eb}'..='\u{112ef}',
                '\u{112fa}'..='\u{112ff}',
                '\u{11304}'..='\u{11304}',
                '\u{1130d}'..='\u{1130e}',
                '\u{11311}'..='\u{11312}',
                '\u{11329}'..='\u{11329}',
                '\u{11331}'..='\u{11331}',
                '\u{11334}'..='\u{11334}',
                '\u{1133a}'..='\u{1133a}',
                '\u{11345}'..='\u{11346}',
                '\u{11349}'..='\u{1134a}',
                '\u{1134e}'..='\u{1134f}',
                '\u{11351}'..='\u{11356}',
                '\u{11358}'..='\u{1135c}',
                '\u{11364}'..='\u{11365}',
                '\u{1136d}'..='\u{1136f}',
                '\u{11375}'..='\u{1137f}',
                '\u{1138a}'..='\u{1138a}',
                '\u{1138c}'..='\u{1138d}',
                '\u{1138f}'..='\u{1138f}',
                '\u{113b6}'..='\u{113b6}',
                '\u{113c1}'..='\u{113c1}',
                '\u{113c3}'..='\u{113c4}',
                '\u{113c6}'..='\u{113c6}',
                '\u{113cb}'..='\u{113cb}',
                '𑏔'..='\u{113e0}',
                '\u{113e3}'..='\u{113ff}',
                '𑑋'..='𑑏',
                '𑑚'..='𑑝',
                '\u{11462}'..='\u{1147f}',
                '𑓆'..='𑓆',
                '\u{114c8}'..='\u{114cf}',
                '\u{114da}'..='\u{1157f}',
                '\u{115b6}'..='\u{115b7}',
                '𑗁'..='𑗗',
                '\u{115de}'..='\u{115ff}',
                '𑙁'..='𑙃',
                '\u{11645}'..='\u{1164f}',
                '\u{1165a}'..='\u{1167f}',
                '𑚹'..='\u{116bf}',
                '\u{116ca}'..='\u{116cf}',
                '\u{116e4}'..='\u{116ff}',
                '\u{1171b}'..='\u{1171c}',
                '\u{1172c}'..='\u{1172f}',
                '𑜺'..='𑜿',
                '\u{11747}'..='\u{117ff}',
                '𑠻'..='\u{1189f}',
                '𑣪'..='\u{118fe}',
                '\u{11907}'..='\u{11908}',
                '\u{1190a}'..='\u{1190b}',
                '\u{11914}'..='\u{11914}',
                '\u{11917}'..='\u{11917}',
                '\u{11936}'..='\u{11936}',
                '\u{11939}'..='\u{1193a}',
                '𑥄'..='\u{1194f}',
                '\u{1195a}'..='\u{1199f}',
                '\u{119a8}'..='\u{119a9}',
                '\u{119d8}'..='\u{119d9}',
                '𑧢'..='𑧢',
                '\u{119e5}'..='\u{119ff}',
                '𑨿'..='𑩆',
                '\u{11a48}'..='\u{11a4f}',
                '𑪚'..='𑪜',
                '𑪞'..='\u{11aaf}',
                '\u{11af9}'..='\u{11bbf}',
                '𑯡'..='\u{11bef}',
                '\u{11bfa}'..='\u{11bff}',
                '\u{11c09}'..='\u{11c09}',
                '\u{11c37}'..='\u{11c37}',
                '𑱁'..='\u{11c4f}',
                '𑱚'..='𑱱',
                '\u{11c90}'..='\u{11c91}',
                '\u{11ca8}'..='\u{11ca8}',
                '\u{11cb7}'..='\u{11cff}',
                '\u{11d07}'..='\u{11d07}',
                '\u{11d0a}'..='\u{11d0a}',
                '\u{11d37}'..='\u{11d39}',
                '\u{11d3b}'..='\u{11d3b}',
                '\u{11d3e}'..='\u{11d3e}',
                '\u{11d48}'..='\u{11d4f}',
                '\u{11d5a}'..='\u{11d5f}',
                '\u{11d66}'..='\u{11d66}',
                '\u{11d69}'..='\u{11d69}',
                '\u{11d8f}'..='\u{11d8f}',
                '\u{11d92}'..='\u{11d92}',
                '\u{11d99}'..='\u{11d9f}',
                '\u{11daa}'..='\u{11edf}',
                '𑻷'..='\u{11eff}',
                '\u{11f11}'..='\u{11f11}',
                '\u{11f3b}'..='\u{11f3d}',
                '𑽃'..='𑽏',
                '\u{11f5b}'..='\u{11faf}',
                '\u{11fb1}'..='𑿿',
                '\u{1239a}'..='\u{123ff}',
                '\u{1246f}'..='\u{1247f}',
                '\u{12544}'..='\u{12f8f}',
                '𒿱'..='\u{12fff}',
                '\u{13430}'..='\u{1343f}',
                '\u{13456}'..='\u{1345f}',
                '\u{143fb}'..='\u{143ff}',
                '\u{14647}'..='\u{160ff}',
                '\u{1613a}'..='\u{167ff}',
                '\u{16a39}'..='\u{16a3f}',
                '\u{16a5f}'..='\u{16a5f}',
                '\u{16a6a}'..='𖩯',
                '\u{16abf}'..='\u{16abf}',
                '\u{16aca}'..='\u{16acf}',
                '\u{16aee}'..='\u{16aef}',
                '𖫵'..='\u{16aff}',
                '𖬷'..='𖬿',
                '𖭄'..='\u{16b4f}',
                '\u{16b5a}'..='\u{16b62}',
                '\u{16b78}'..='\u{16b7c}',
                '\u{16b90}'..='\u{16d3f}',
                '𖵭'..='𖵯',
                '\u{16d7a}'..='\u{16e3f}',
                '𖺀'..='\u{16eff}',
                '\u{16f4b}'..='\u{16f4e}',
                '\u{16f88}'..='\u{16f8e}',
                '\u{16fa0}'..='\u{16fdf}',
                '𖿢'..='𖿢',
                '\u{16fe5}'..='\u{16fef}',
                '\u{16ff2}'..='\u{16fff}',
                '\u{187f8}'..='\u{187ff}',
                '\u{18cd6}'..='\u{18cfe}',
                '\u{18d09}'..='\u{1afef}',
                '\u{1aff4}'..='\u{1aff4}',
                '\u{1affc}'..='\u{1affc}',
                '\u{1afff}'..='\u{1afff}',
                '\u{1b123}'..='\u{1b131}',
                '\u{1b133}'..='\u{1b14f}',
                '\u{1b153}'..='\u{1b154}',
                '\u{1b156}'..='\u{1b163}',
                '\u{1b168}'..='\u{1b16f}',
                '\u{1b2fc}'..='\u{1bbff}',
                '\u{1bc6b}'..='\u{1bc6f}',
                '\u{1bc7d}'..='\u{1bc7f}',
                '\u{1bc89}'..='\u{1bc8f}',
                '\u{1bc9a}'..='𛲜',
                '𛲟'..='𜳯',
                '\u{1ccfa}'..='\u{1ceff}',
                '\u{1cf2e}'..='\u{1cf2f}',
                '\u{1cf47}'..='𝅘𝅥𝅲',
                '𝅪'..='𝅬',
                '\u{1d173}'..='\u{1d17a}',
                '𝆃'..='𝆄',
                '𝆌'..='𝆩',
                '𝆮'..='𝉁',
                '𝉅'..='\u{1d3ff}',
                '\u{1d455}'..='\u{1d455}',
                '\u{1d49d}'..='\u{1d49d}',
                '\u{1d4a0}'..='\u{1d4a1}',
                '\u{1d4a3}'..='\u{1d4a4}',
                '\u{1d4a7}'..='\u{1d4a8}',
                '\u{1d4ad}'..='\u{1d4ad}',
                '\u{1d4ba}'..='\u{1d4ba}',
                '\u{1d4bc}'..='\u{1d4bc}',
                '\u{1d4c4}'..='\u{1d4c4}',
                '\u{1d506}'..='\u{1d506}',
                '\u{1d50b}'..='\u{1d50c}',
                '\u{1d515}'..='\u{1d515}',
                '\u{1d51d}'..='\u{1d51d}',
                '\u{1d53a}'..='\u{1d53a}',
                '\u{1d53f}'..='\u{1d53f}',
                '\u{1d545}'..='\u{1d545}',
                '\u{1d547}'..='\u{1d549}',
                '\u{1d551}'..='\u{1d551}',
                '\u{1d6a6}'..='\u{1d6a7}',
                '𝛁'..='𝛁',
                '𝛛'..='𝛛',
                '𝛻'..='𝛻',
                '𝜕'..='𝜕',
                '𝜵'..='𝜵',
                '𝝏'..='𝝏',
                '𝝯'..='𝝯',
                '𝞉'..='𝞉',
                '𝞩'..='𝞩',
                '𝟃'..='𝟃',
                '\u{1d7cc}'..='\u{1d7cd}',
                '𝠀'..='𝧿',
                '𝨷'..='𝨺',
                '𝩭'..='𝩴',
                '𝩶'..='𝪃',
                '𝪅'..='\u{1da9a}',
                '\u{1daa0}'..='\u{1daa0}',
                '\u{1dab0}'..='\u{1deff}',
                '\u{1df1f}'..='\u{1df24}',
                '\u{1df2b}'..='\u{1dfff}',
                '\u{1e007}'..='\u{1e007}',
                '\u{1e019}'..='\u{1e01a}',
                '\u{1e022}'..='\u{1e022}',
                '\u{1e025}'..='\u{1e025}',
                '\u{1e02b}'..='\u{1e02f}',
                '\u{1e06e}'..='\u{1e08e}',
                '\u{1e090}'..='\u{1e0ff}',
                '\u{1e12d}'..='\u{1e12f}',
                '\u{1e13e}'..='\u{1e13f}',
                '\u{1e14a}'..='\u{1e14d}',
                '𞅏'..='\u{1e28f}',
                '\u{1e2af}'..='\u{1e2bf}',
                '\u{1e2fa}'..='\u{1e4cf}',
                '\u{1e4fa}'..='\u{1e5cf}',
                '\u{1e5fb}'..='\u{1e7df}',
                '\u{1e7e7}'..='\u{1e7e7}',
                '\u{1e7ec}'..='\u{1e7ec}',
                '\u{1e7ef}'..='\u{1e7ef}',
                '\u{1e7ff}'..='\u{1e7ff}',
                '\u{1e8c5}'..='𞣏',
                '\u{1e8d7}'..='\u{1e8ff}',
                '\u{1e94c}'..='\u{1e94f}',
                '\u{1e95a}'..='\u{1edff}',
                '\u{1ee04}'..='\u{1ee04}',
                '\u{1ee20}'..='\u{1ee20}',
                '\u{1ee23}'..='\u{1ee23}',
                '\u{1ee25}'..='\u{1ee26}',
                '\u{1ee28}'..='\u{1ee28}',
                '\u{1ee33}'..='\u{1ee33}',
                '\u{1ee38}'..='\u{1ee38}',
                '\u{1ee3a}'..='\u{1ee3a}',
                '\u{1ee3c}'..='\u{1ee41}',
                '\u{1ee43}'..='\u{1ee46}',
                '\u{1ee48}'..='\u{1ee48}',
                '\u{1ee4a}'..='\u{1ee4a}',
                '\u{1ee4c}'..='\u{1ee4c}',
                '\u{1ee50}'..='\u{1ee50}',
                '\u{1ee53}'..='\u{1ee53}',
                '\u{1ee55}'..='\u{1ee56}',
                '\u{1ee58}'..='\u{1ee58}',
                '\u{1ee5a}'..='\u{1ee5a}',
                '\u{1ee5c}'..='\u{1ee5c}',
                '\u{1ee5e}'..='\u{1ee5e}',
                '\u{1ee60}'..='\u{1ee60}',
                '\u{1ee63}'..='\u{1ee63}',
                '\u{1ee65}'..='\u{1ee66}',
                '\u{1ee6b}'..='\u{1ee6b}',
                '\u{1ee73}'..='\u{1ee73}',
                '\u{1ee78}'..='\u{1ee78}',
                '\u{1ee7d}'..='\u{1ee7d}',
                '\u{1ee7f}'..='\u{1ee7f}',
                '\u{1ee8a}'..='\u{1ee8a}',
                '\u{1ee9c}'..='\u{1eea0}',
                '\u{1eea4}'..='\u{1eea4}',
                '\u{1eeaa}'..='\u{1eeaa}',
                '\u{1eebc}'..='🄯',
                '🅊'..='🅏',
                '🅪'..='🅯',
                '🆊'..='🯯',
                '\u{1fbfa}'..='\u{1ffff}',
                '\u{2a6e0}'..='\u{2a6ff}',
                '\u{2b73a}'..='\u{2b73f}',
                '\u{2b81e}'..='\u{2b81f}',
                '\u{2cea2}'..='\u{2ceaf}',
                '\u{2ebe1}'..='\u{2ebef}',
                '\u{2ee5e}'..='\u{2f7ff}',
                '\u{2fa1e}'..='\u{2ffff}',
                '\u{3134b}'..='\u{3134f}',
                '\u{323b0}'..='\u{e00ff}',
                '\u{e01f0}'..='\u{10fffe}',
            ],
            &[
                '\t'..='\t',
                '\u{b}'..='\u{c}',
                ' '..=' ',
                '\u{85}'..='\u{85}',
                '\u{a0}'..='\u{a0}',
                '\u{1680}'..='\u{1680}',
                '\u{2000}'..='\u{200a}',
                '\u{2028}'..='\u{2029}',
                '\u{202f}'..='\u{202f}',
                '\u{205f}'..='\u{205f}',
                '\u{3000}'..='\u{3000}',
            ],
            &['\n'..='\n'],
            &['\r'..='\r'],
            &['!'..='!'],
            &['"'..='"'],
            &['*'..='*'],
            &['/'..='/'],
            &[
                '0'..='9',
                'ª'..='ª',
                'µ'..='µ',
                'º'..='º',
                'À'..='Ö',
                'Ø'..='ö',
                'ø'..='ˁ',
                'ˆ'..='ˑ',
                'ˠ'..='ˤ',
                'ˬ'..='ˬ',
                'ˮ'..='ˮ',
                '\u{300}'..='ʹ',
                'Ͷ'..='ͷ',
                'ͺ'..='ͽ',
                'Ϳ'..='Ϳ',
                'Ά'..='Ά',
                'Έ'..='Ί',
                'Ό'..='Ό',
                'Ύ'..='Ρ',
                'Σ'..='ϵ',
                'Ϸ'..='ҁ',
                '\u{483}'..='ԯ',
                'Ա'..='Ֆ',
                'ՙ'..='ՙ',
                'ՠ'..='ֈ',
                '\u{591}'..='\u{5bd}',
                '\u{5bf}'..='\u{5bf}',
                '\u{5c1}'..='\u{5c2}',
                '\u{5c4}'..='\u{5c5}',
                '\u{5c7}'..='\u{5c7}',
                'א'..='ת',
                'ׯ'..='ײ',
                '\u{610}'..='\u{61a}',
                'ؠ'..='٩',
                'ٮ'..='ۓ',
                'ە'..='\u{6dc}',
                '\u{6df}'..='\u{6e8}',
                '\u{6ea}'..='ۼ',
                'ۿ'..='ۿ',
                'ܐ'..='\u{74a}',
                'ݍ'..='ޱ',
                '߀'..='ߵ',
                'ߺ'..='ߺ',
                '\u{7fd}'..='\u{7fd}',
                'ࠀ'..='\u{82d}',
                'ࡀ'..='\u{85b}',
                'ࡠ'..='ࡪ',
                'ࡰ'..='ࢇ',
                'ࢉ'..='ࢎ',
                '\u{897}'..='\u{8e1}',
                '\u{8e3}'..='\u{963}',
                '०'..='९',
                'ॱ'..='ঃ',
                'অ'..='ঌ',
                'এ'..='ঐ',
                'ও'..='ন',
                'প'..='র',
                'ল'..='ল',
                'শ'..='হ',
                '\u{9bc}'..='\u{9c4}',
                'ে'..='ৈ',
                'ো'..='ৎ',
                '\u{9d7}'..='\u{9d7}',
                'ড়'..='ঢ়',
                'য়'..='\u{9e3}',
                '০'..='ৱ',
                'ৼ'..='ৼ',
                '\u{9fe}'..='\u{9fe}',
                '\u{a01}'..='ਃ',
                'ਅ'..='ਊ',
                'ਏ'..='ਐ',
                'ਓ'..='ਨ',
                'ਪ'..='ਰ',
                'ਲ'..='ਲ਼',
                'ਵ'..='ਸ਼',
                'ਸ'..='ਹ',
                '\u{a3c}'..='\u{a3c}',
                'ਾ'..='\u{a42}',
                '\u{a47}'..='\u{a48}',
                '\u{a4b}'..='\u{a4d}',
                '\u{a51}'..='\u{a51}',
                'ਖ਼'..='ੜ',
                'ਫ਼'..='ਫ਼',
                '੦'..='\u{a75}',
                '\u{a81}'..='ઃ',
                'અ'..='ઍ',
                'એ'..='ઑ',
                'ઓ'..='ન',
                'પ'..='ર',
                'લ'..='ળ',
                'વ'..='હ',
                '\u{abc}'..='\u{ac5}',
                '\u{ac7}'..='ૉ',
                'ો'..='\u{acd}',
                'ૐ'..='ૐ',
                'ૠ'..='\u{ae3}',
                '૦'..='૯',
                'ૹ'..='\u{aff}',
                '\u{b01}'..='ଃ',
                'ଅ'..='ଌ',
                'ଏ'..='ଐ',
                'ଓ'..='ନ',
                'ପ'..='ର',
                'ଲ'..='ଳ',
                'ଵ'..='ହ',
                '\u{b3c}'..='\u{b44}',
                'େ'..='ୈ',
                'ୋ'..='\u{b4d}',
                '\u{b55}'..='\u{b57}',
                'ଡ଼'..='ଢ଼',
                'ୟ'..='\u{b63}',
                '୦'..='୯',
                'ୱ'..='ୱ',
                '\u{b82}'..='ஃ',
                'அ'..='ஊ',
                'எ'..='ஐ',
                'ஒ'..='க',
                'ங'..='ச',
                'ஜ'..='ஜ',
                'ஞ'..='ட',
                'ண'..='த',
                'ந'..='ப',
                'ம'..='ஹ',
                '\u{bbe}'..='ூ',
                'ெ'..='ை',
                'ொ'..='\u{bcd}',
                'ௐ'..='ௐ',
                '\u{bd7}'..='\u{bd7}',
                '௦'..='௯',
                '\u{c00}'..='ఌ',
                'ఎ'..='ఐ',
                'ఒ'..='న',
                'ప'..='హ',
                '\u{c3c}'..='ౄ',
                '\u{c46}'..='\u{c48}',
                '\u{c4a}'..='\u{c4d}',
                '\u{c55}'..='\u{c56}',
                'ౘ'..='ౚ',
                'ౝ'..='ౝ',
                'ౠ'..='\u{c63}',
                '౦'..='౯',
                'ಀ'..='ಃ',
                'ಅ'..='ಌ',
                'ಎ'..='ಐ',
                'ಒ'..='ನ',
                'ಪ'..='ಳ',
                'ವ'..='ಹ',
                '\u{cbc}'..='ೄ',
                '\u{cc6}'..='\u{cc8}',
                '\u{cca}'..='\u{ccd}',
                '\u{cd5}'..='\u{cd6}',
                'ೝ'..='ೞ',
                'ೠ'..='\u{ce3}',
                '೦'..='೯',
                'ೱ'..='ೳ',
                '\u{d00}'..='ഌ',
                'എ'..='ഐ',
                'ഒ'..='\u{d44}',
                'െ'..='ൈ',
                'ൊ'..='ൎ',
                'ൔ'..='\u{d57}',
                'ൟ'..='\u{d63}',
                '൦'..='൯',
                'ൺ'..='ൿ',
                '\u{d81}'..='ඃ',
                'අ'..='ඖ',
                'ක'..='න',
                'ඳ'..='ර',
                'ල'..='ල',
                'ව'..='ෆ',
                '\u{dca}'..='\u{dca}',
                '\u{dcf}'..='\u{dd4}',
                '\u{dd6}'..='\u{dd6}',
                'ෘ'..='\u{ddf}',
                '෦'..='෯',
                'ෲ'..='ෳ',
                'ก'..='\u{e3a}',
                'เ'..='\u{e4e}',
                '๐'..='๙',
                'ກ'..='ຂ',
                'ຄ'..='ຄ',
                'ຆ'..='ຊ',
                'ຌ'..='ຣ',
                'ລ'..='ລ',
                'ວ'..='ຽ',
                'ເ'..='ໄ',
                'ໆ'..='ໆ',
                '\u{ec8}'..='\u{ece}',
                '໐'..='໙',
                'ໜ'..='ໟ',
                'ༀ'..='ༀ',
                '\u{f18}'..='\u{f19}',
                '༠'..='༩',
                '\u{f35}'..='\u{f35}',
                '\u{f37}'..='\u{f37}',
                '\u{f39}'..='\u{f39}',
                '༾'..='ཇ',
                'ཉ'..='ཬ',
                '\u{f71}'..='\u{f84}',
                '\u{f86}'..='\u{f97}',
                '\u{f99}'..='\u{fbc}',
                '\u{fc6}'..='\u{fc6}',
                'က'..='၉',
                'ၐ'..='\u{109d}',
                'Ⴀ'..='Ⴥ',
                'Ⴧ'..='Ⴧ',
                'Ⴭ'..='Ⴭ',
                'ა'..='ჺ',
                'ჼ'..='ቈ',
                'ቊ'..='ቍ',
                'ቐ'..='ቖ',
                'ቘ'..='ቘ',
                'ቚ'..='ቝ',
                'በ'..='ኈ',
                'ኊ'..='ኍ',
                'ነ'..='ኰ',
                'ኲ'..='ኵ',
                'ኸ'..='ኾ',
                'ዀ'..='ዀ',
                'ዂ'..='ዅ',
                'ወ'..='ዖ',
                'ዘ'..='ጐ',
                'ጒ'..='ጕ',
                'ጘ'..='ፚ',
                '\u{135d}'..='\u{135f}',
                'ᎀ'..='ᎏ',
                'Ꭰ'..='Ᏽ',
                'ᏸ'..='ᏽ',
                'ᐁ'..='ᙬ',
                'ᙯ'..='ᙿ',
                'ᚁ'..='ᚚ',
                'ᚠ'..='ᛪ',
                'ᛮ'..='ᛸ',
                'ᜀ'..='\u{1715}',
                'ᜟ'..='\u{1734}',
                'ᝀ'..='\u{1753}',
                'ᝠ'..='ᝬ',
                'ᝮ'..='ᝰ',
                '\u{1772}'..='\u{1773}',
                'ក'..='\u{17d3}',
                'ៗ'..='ៗ',
                'ៜ'..='\u{17dd}',
                '០'..='៩',
                '\u{180b}'..='\u{180d}',
                '\u{180f}'..='᠙',
                'ᠠ'..='ᡸ',
                'ᢀ'..='ᢪ',
                'ᢰ'..='ᣵ',
                'ᤀ'..='ᤞ',
                '\u{1920}'..='ᤫ',
                'ᤰ'..='\u{193b}',
                '᥆'..='ᥭ',
                'ᥰ'..='ᥴ',
                'ᦀ'..='ᦫ',
                'ᦰ'..='ᧉ',
                '᧐'..='᧙',
                'ᨀ'..='\u{1a1b}',
                'ᨠ'..='\u{1a5e}',
                '\u{1a60}'..='\u{1a7c}',
                '\u{1a7f}'..='᪉',
                '᪐'..='᪙',
                'ᪧ'..='ᪧ',
                '\u{1ab0}'..='\u{1ace}',
                '\u{1b00}'..='ᭌ',
                '᭐'..='᭙',
                '\u{1b6b}'..='\u{1b73}',
                '\u{1b80}'..='\u{1bf3}',
                'ᰀ'..='\u{1c37}',
                '᱀'..='᱉',
                'ᱍ'..='ᱽ',
                'ᲀ'..='ᲊ',
                'Ა'..='Ჺ',
                'Ჽ'..='Ჿ',
                '\u{1cd0}'..='\u{1cd2}',
                '\u{1cd4}'..='ᳺ',
                'ᴀ'..='ἕ',
                'Ἐ'..='Ἕ',
                'ἠ'..='ὅ',
                'Ὀ'..='Ὅ',
                'ὐ'..='ὗ',
                'Ὑ'..='Ὑ',
                'Ὓ'..='Ὓ',
                'Ὕ'..='Ὕ',
                'Ὗ'..='ώ',
                'ᾀ'..='ᾴ',
                'ᾶ'..='ᾼ',
                'ι'..='ι',
                'ῂ'..='ῄ',
                'ῆ'..='ῌ',
                'ῐ'..='ΐ',
                'ῖ'..='Ί',
                'ῠ'..='Ῥ',
                'ῲ'..='ῴ',
                'ῶ'..='ῼ',
                '\u{200c}'..='\u{200d}',
                '‿'..='⁀',
                '⁔'..='⁔',
                'ⁱ'..='ⁱ',
                'ⁿ'..='ⁿ',
                'ₐ'..='ₜ',
                '\u{20d0}'..='\u{20f0}',
                'ℂ'..='ℂ',
                'ℇ'..='ℇ',
                'ℊ'..='ℓ',
                'ℕ'..='ℕ',
                'ℙ'..='ℝ',
                'ℤ'..='ℤ',
                'Ω'..='Ω',
                'ℨ'..='ℨ',
                'K'..='ℭ',
                'ℯ'..='ℹ',
                'ℼ'..='ℿ',
                'ⅅ'..='ⅉ',
                'ⅎ'..='ⅎ',
                'Ⅰ'..='ↈ',
                'Ⓐ'..='ⓩ',
                'Ⰰ'..='ⳤ',
                'Ⳬ'..='ⳳ',
                'ⴀ'..='ⴥ',
                'ⴧ'..='ⴧ',
                'ⴭ'..='ⴭ',
                'ⴰ'..='ⵧ',
                'ⵯ'..='ⵯ',
                '\u{2d7f}'..='ⶖ',
                'ⶠ'..='ⶦ',
                'ⶨ'..='ⶮ',
                'ⶰ'..='ⶶ',
                'ⶸ'..='ⶾ',
                'ⷀ'..='ⷆ',
                'ⷈ'..='ⷎ',
                'ⷐ'..='ⷖ',
                'ⷘ'..='ⷞ',
                '\u{2de0}'..='\u{2dff}',
                'ⸯ'..='ⸯ',
                '々'..='〇',
                '〡'..='\u{302f}',
                '〱'..='〵',
                '〸'..='〼',
                'ぁ'..='ゖ',
                '\u{3099}'..='\u{309a}',
                'ゝ'..='ゟ',
                'ァ'..='ヺ',
                'ー'..='ヿ',
                'ㄅ'..='ㄯ',
                'ㄱ'..='ㆎ',
                'ㆠ'..='ㆿ',
                'ㇰ'..='ㇿ',
                '㐀'..='䶿',
                '一'..='ꒌ',
                'ꓐ'..='ꓽ',
                'ꔀ'..='ꘌ',
                'ꘐ'..='ꘫ',
                'Ꙁ'..='\u{a672}',
                '\u{a674}'..='\u{a67d}',
                'ꙿ'..='\u{a6f1}',
                'ꜗ'..='ꜟ',
                'Ꜣ'..='ꞈ',
                'Ꞌ'..='ꟍ',
                'Ꟑ'..='ꟑ',
                'ꟓ'..='ꟓ',
                'ꟕ'..='Ƛ',
                'ꟲ'..='ꠧ',
                '\u{a82c}'..='\u{a82c}',
                'ꡀ'..='ꡳ',
                'ꢀ'..='\u{a8c5}',
                '꣐'..='꣙',
                '\u{a8e0}'..='ꣷ',
                'ꣻ'..='ꣻ',
                'ꣽ'..='\u{a92d}',
                'ꤰ'..='\u{a953}',
                'ꥠ'..='ꥼ',
                '\u{a980}'..='\u{a9c0}',
                'ꧏ'..='꧙',
                'ꧠ'..='ꧾ',
                'ꨀ'..='\u{aa36}',
                'ꩀ'..='ꩍ',
                '꩐'..='꩙',
                'ꩠ'..='ꩶ',
                'ꩺ'..='ꫂ',
                'ꫛ'..='ꫝ',
                'ꫠ'..='ꫯ',
                'ꫲ'..='\u{aaf6}',
                'ꬁ'..='ꬆ',
                'ꬉ'..='ꬎ',
                'ꬑ'..='ꬖ',
                'ꬠ'..='ꬦ',
                'ꬨ'..='ꬮ',
                'ꬰ'..='ꭚ',
                'ꭜ'..='ꭩ',
                'ꭰ'..='ꯪ',
                '꯬'..='\u{abed}',
                '꯰'..='꯹',
                '가'..='힣',
                'ힰ'..='ퟆ',
                'ퟋ'..='ퟻ',
                '豈'..='舘',
                '並'..='龎',
                'ﬀ'..='ﬆ',
                'ﬓ'..='ﬗ',
                'יִ'..='ﬨ',
                'שׁ'..='זּ',
                'טּ'..='לּ',
                'מּ'..='מּ',
                'נּ'..='סּ',
                'ףּ'..='פּ',
                'צּ'..='ﮱ',
                'ﯓ'..='ﴽ',
                'ﵐ'..='ﶏ',
                'ﶒ'..='ﷇ',
                'ﷰ'..='ﷻ',
                '\u{fe00}'..='\u{fe0f}',
                '\u{fe20}'..='\u{fe2f}',
                '︳'..='︴',
                '﹍'..='﹏',
                'ﹰ'..='ﹴ',
                'ﹶ'..='ﻼ',
                '０'..='９',
                'Ａ'..='Ｚ',
                '＿'..='＿',
                'ａ'..='ｚ',
                'ｦ'..='ﾾ',
                'ￂ'..='ￇ',
                'ￊ'..='ￏ',
                'ￒ'..='ￗ',
                'ￚ'..='ￜ',
                '𐀀'..='𐀋',
                '𐀍'..='𐀦',
                '𐀨'..='𐀺',
                '𐀼'..='𐀽',
                '𐀿'..='𐁍',
                '𐁐'..='𐁝',
                '𐂀'..='𐃺',
                '𐅀'..='𐅴',
                '\u{101fd}'..='\u{101fd}',
                '𐊀'..='𐊜',
                '𐊠'..='𐋐',
                '\u{102e0}'..='\u{102e0}',
                '𐌀'..='𐌟',
                '𐌭'..='𐍊',
                '𐍐'..='\u{1037a}',
                '𐎀'..='𐎝',
                '𐎠'..='𐏃',
                '𐏈'..='𐏏',
                '𐏑'..='𐏕',
                '𐐀'..='𐒝',
                '𐒠'..='𐒩',
                '𐒰'..='𐓓',
                '𐓘'..='𐓻',
                '𐔀'..='𐔧',
                '𐔰'..='𐕣',
                '𐕰'..='𐕺',
                '𐕼'..='𐖊',
                '𐖌'..='𐖒',
                '𐖔'..='𐖕',
                '𐖗'..='𐖡',
                '𐖣'..='𐖱',
                '𐖳'..='𐖹',
                '𐖻'..='𐖼',
                '𐗀'..='𐗳',
                '𐘀'..='𐜶',
                '𐝀'..='𐝕',
                '𐝠'..='𐝧',
                '𐞀'..='𐞅',
                '𐞇'..='𐞰',
                '𐞲'..='𐞺',
                '𐠀'..='𐠅',
                '𐠈'..='𐠈',
                '𐠊'..='𐠵',
                '𐠷'..='𐠸',
                '𐠼'..='𐠼',
                '𐠿'..='𐡕',
                '𐡠'..='𐡶',
                '𐢀'..='𐢞',
                '𐣠'..='𐣲',
                '𐣴'..='𐣵',
                '𐤀'..='𐤕',
                '𐤠'..='𐤹',
                '𐦀'..='𐦷',
                '𐦾'..='𐦿',
                '𐨀'..='\u{10a03}',
                '\u{10a05}'..='\u{10a06}',
                '\u{10a0c}'..='𐨓',
                '𐨕'..='𐨗',
                '𐨙'..='𐨵',
                '\u{10a38}'..='\u{10a3a}',
                '\u{10a3f}'..='\u{10a3f}',
                '𐩠'..='𐩼',
                '𐪀'..='𐪜',
                '𐫀'..='𐫇',
                '𐫉'..='\u{10ae6}',
                '𐬀'..='𐬵',
                '𐭀'..='𐭕',
                '𐭠'..='𐭲',
                '𐮀'..='𐮑',
                '𐰀'..='𐱈',
                '𐲀'..='𐲲',
                '𐳀'..='𐳲',
                '𐴀'..='\u{10d27}',
                '𐴰'..='𐴹',
                '𐵀'..='𐵥',
                '\u{10d69}'..='\u{10d6d}',
                '𐵯'..='𐶅',
                '𐺀'..='𐺩',
                '\u{10eab}'..='\u{10eac}',
                '𐺰'..='𐺱',
                '𐻂'..='𐻄',
                '\u{10efc}'..='𐼜',
                '𐼧'..='𐼧',
                '𐼰'..='\u{10f50}',
                '𐽰'..='\u{10f85}',
                '𐾰'..='𐿄',
                '𐿠'..='𐿶',
                '𑀀'..='\u{11046}',
                '𑁦'..='𑁵',
                '\u{1107f}'..='\u{110ba}',
                '\u{110c2}'..='\u{110c2}',
                '𑃐'..='𑃨',
                '𑃰'..='𑃹',
                '\u{11100}'..='\u{11134}',
                '𑄶'..='𑄿',
                '𑅄'..='𑅇',
                '𑅐'..='\u{11173}',
                '𑅶'..='𑅶',
                '\u{11180}'..='𑇄',
                '\u{111c9}'..='\u{111cc}',
                '𑇎'..='𑇚',
                '𑇜'..='𑇜',
                '𑈀'..='𑈑',
                '𑈓'..='\u{11237}',
                '\u{1123e}'..='\u{11241}',
                '𑊀'..='𑊆',
                '𑊈'..='𑊈',
                '𑊊'..='𑊍',
                '𑊏'..='𑊝',
                '𑊟'..='𑊨',
                '𑊰'..='\u{112ea}',
                '𑋰'..='𑋹',
                '\u{11300}'..='𑌃',
                '𑌅'..='𑌌',
                '𑌏'..='𑌐',
                '𑌓'..='𑌨',
                '𑌪'..='𑌰',
                '𑌲'..='𑌳',
                '𑌵'..='𑌹',
                '\u{1133b}'..='𑍄',
                '𑍇'..='𑍈',
                '𑍋'..='\u{1134d}',
                '𑍐'..='𑍐',
                '\u{11357}'..='\u{11357}',
                '𑍝'..='𑍣',
                '\u{11366}'..='\u{1136c}',
                '\u{11370}'..='\u{11374}',
                '𑎀'..='𑎉',
                '𑎋'..='𑎋',
                '𑎎'..='𑎎',
                '𑎐'..='𑎵',
                '𑎷'..='\u{113c0}',
                '\u{113c2}'..='\u{113c2}',
                '\u{113c5}'..='\u{113c5}',
                '\u{113c7}'..='𑏊',
                '𑏌'..='𑏓',
                '\u{113e1}'..='\u{113e2}',
                '𑐀'..='𑑊',
                '𑑐'..='𑑙',
                '\u{1145e}'..='𑑡',
                '𑒀'..='𑓅',
                '𑓇'..='𑓇',
                '𑓐'..='𑓙',
                '𑖀'..='\u{115b5}',
                '𑖸'..='\u{115c0}',
                '𑗘'..='\u{115dd}',
                '𑘀'..='\u{11640}',
                '𑙄'..='𑙄',
                '𑙐'..='𑙙',
                '𑚀'..='𑚸',
                '𑛀'..='𑛉',
                '𑛐'..='𑛣',
                '𑜀'..='𑜚',
                '\u{1171d}'..='\u{1172b}',
                '𑜰'..='𑜹',
                '𑝀'..='𑝆',
                '𑠀'..='\u{1183a}',
                '𑢠'..='𑣩',
                '𑣿'..='𑤆',
                '𑤉'..='𑤉',
                '𑤌'..='𑤓',
                '𑤕'..='𑤖',
                '𑤘'..='𑤵',
                '𑤷'..='𑤸',
                '\u{1193b}'..='\u{11943}',
                '𑥐'..='𑥙',
                '𑦠'..='𑦧',
                '𑦪'..='\u{119d7}',
                '\u{119da}'..='𑧡',
                '𑧣'..='𑧤',
                '𑨀'..='\u{11a3e}',
                '\u{11a47}'..='\u{11a47}',
                '𑩐'..='\u{11a99}',
                '𑪝'..='𑪝',
                '𑪰'..='𑫸',
                '𑯀'..='𑯠',
                '𑯰'..='𑯹',
                '𑰀'..='𑰈',
                '𑰊'..='\u{11c36}',
                '\u{11c38}'..='𑱀',
                '𑱐'..='𑱙',
                '𑱲'..='𑲏',
                '\u{11c92}'..='\u{11ca7}',
                '𑲩'..='\u{11cb6}',
                '𑴀'..='𑴆',
                '𑴈'..='𑴉',
                '𑴋'..='\u{11d36}',
                '\u{11d3a}'..='\u{11d3a}',
                '\u{11d3c}'..='\u{11d3d}',
                '\u{11d3f}'..='\u{11d47}',
                '𑵐'..='𑵙',
                '𑵠'..='𑵥',
                '𑵧'..='𑵨',
                '𑵪'..='𑶎',
                '\u{11d90}'..='\u{11d91}',
                '𑶓'..='𑶘',
                '𑶠'..='𑶩',
                '𑻠'..='𑻶',
                '\u{11f00}'..='𑼐',
                '𑼒'..='\u{11f3a}',
                '𑼾'..='\u{11f42}',
                '𑽐'..='\u{11f5a}',
                '𑾰'..='𑾰',
                '𒀀'..='𒎙',
                '𒐀'..='𒑮',
                '𒒀'..='𒕃',
                '𒾐'..='𒿰',
                '𓀀'..='𓐯',
                '\u{13440}'..='\u{13455}',
                '𓑠'..='𔏺',
                '𔐀'..='𔙆',
                '𖄀'..='𖄹',
                '𖠀'..='𖨸',
                '𖩀'..='𖩞',
                '𖩠'..='𖩩',
                '𖩰'..='𖪾',
                '𖫀'..='𖫉',
                '𖫐'..='𖫭',
                '\u{16af0}'..='\u{16af4}',
                '𖬀'..='\u{16b36}',
                '𖭀'..='𖭃',
                '𖭐'..='𖭙',
                '𖭣'..='𖭷',
                '𖭽'..='𖮏',
                '𖵀'..='𖵬',
                '𖵰'..='𖵹',
                '𖹀'..='𖹿',
                '𖼀'..='𖽊',
                '\u{16f4f}'..='𖾇',
                '\u{16f8f}'..='𖾟',
                '𖿠'..='𖿡',
                '𖿣'..='\u{16fe4}',
                '\u{16ff0}'..='\u{16ff1}',
                '𗀀'..='𘟷',
                '𘠀'..='𘳕',
                '𘳿'..='𘴈',
                '𚿰'..='𚿳',
                '𚿵'..='𚿻',
                '𚿽'..='𚿾',
                '𛀀'..='𛄢',
                '𛄲'..='𛄲',
                '𛅐'..='𛅒',
                '𛅕'..='𛅕',
                '𛅤'..='𛅧',
                '𛅰'..='𛋻',
                '𛰀'..='𛱪',
                '𛱰'..='𛱼',
                '𛲀'..='𛲈',
                '𛲐'..='𛲙',
                '\u{1bc9d}'..='\u{1bc9e}',
                '𜳰'..='𜳹',
                '\u{1cf00}'..='\u{1cf2d}',
                '\u{1cf30}'..='\u{1cf46}',
                '\u{1d165}'..='\u{1d169}',
                '\u{1d16d}'..='\u{1d172}',
                '\u{1d17b}'..='\u{1d182}',
                '\u{1d185}'..='\u{1d18b}',
                '\u{1d1aa}'..='\u{1d1ad}',
                '\u{1d242}'..='\u{1d244}',
                '𝐀'..='𝑔',
                '𝑖'..='𝒜',
                '𝒞'..='𝒟',
                '𝒢'..='𝒢',
                '𝒥'..='𝒦',
                '𝒩'..='𝒬',
                '𝒮'..='𝒹',
                '𝒻'..='𝒻',
                '𝒽'..='𝓃',
                '𝓅'..='𝔅',
                '𝔇'..='𝔊',
                '𝔍'..='𝔔',
                '𝔖'..='𝔜',
                '𝔞'..='𝔹',
                '𝔻'..='𝔾',
                '𝕀'..='𝕄',
                '𝕆'..='𝕆',
                '𝕊'..='𝕐',
                '𝕒'..='𝚥',
                '𝚨'..='𝛀',
                '𝛂'..='𝛚',
                '𝛜'..='𝛺',
                '𝛼'..='𝜔',
                '𝜖'..='𝜴',
                '𝜶'..='𝝎',
                '𝝐'..='𝝮',
                '𝝰'..='𝞈',
                '𝞊'..='𝞨',
                '𝞪'..='𝟂',
                '𝟄'..='𝟋',
                '𝟎'..='𝟿',
                '\u{1da00}'..='\u{1da36}',
                '\u{1da3b}'..='\u{1da6c}',
                '\u{1da75}'..='\u{1da75}',
                '\u{1da84}'..='\u{1da84}',
                '\u{1da9b}'..='\u{1da9f}',
                '\u{1daa1}'..='\u{1daaf}',
                '𝼀'..='𝼞',
                '𝼥'..='𝼪',
                '\u{1e000}'..='\u{1e006}',
                '\u{1e008}'..='\u{1e018}',
                '\u{1e01b}'..='\u{1e021}',
                '\u{1e023}'..='\u{1e024}',
                '\u{1e026}'..='\u{1e02a}',
                '𞀰'..='𞁭',
                '\u{1e08f}'..='\u{1e08f}',
                '𞄀'..='𞄬',
                '\u{1e130}'..='𞄽',
                '𞅀'..='𞅉',
                '𞅎'..='𞅎',
                '𞊐'..='\u{1e2ae}',
                '𞋀'..='𞋹',
                '𞓐'..='𞓹',
                '𞗐'..='𞗺',
                '𞟠'..='𞟦',
                '𞟨'..='𞟫',
                '𞟭'..='𞟮',
                '𞟰'..='𞟾',
                '𞠀'..='𞣄',
                '\u{1e8d0}'..='\u{1e8d6}',
                '𞤀'..='𞥋',
                '𞥐'..='𞥙',
                '𞸀'..='𞸃',
                '𞸅'..='𞸟',
                '𞸡'..='𞸢',
                '𞸤'..='𞸤',
                '𞸧'..='𞸧',
                '𞸩'..='𞸲',
                '𞸴'..='𞸷',
                '𞸹'..='𞸹',
                '𞸻'..='𞸻',
                '𞹂'..='𞹂',
                '𞹇'..='𞹇',
                '𞹉'..='𞹉',
                '𞹋'..='𞹋',
                '𞹍'..='𞹏',
                '𞹑'..='𞹒',
                '𞹔'..='𞹔',
                '𞹗'..='𞹗',
                '𞹙'..='𞹙',
                '𞹛'..='𞹛',
                '𞹝'..='𞹝',
                '𞹟'..='𞹟',
                '𞹡'..='𞹢',
                '𞹤'..='𞹤',
                '𞹧'..='𞹪',
                '𞹬'..='𞹲',
                '𞹴'..='𞹷',
                '𞹹'..='𞹼',
                '𞹾'..='𞹾',
                '𞺀'..='𞺉',
                '𞺋'..='𞺛',
                '𞺡'..='𞺣',
                '𞺥'..='𞺩',
                '𞺫'..='𞺻',
                '🄰'..='🅉',
                '🅐'..='🅩',
                '🅰'..='🆉',
                '🯰'..='🯹',
                '𠀀'..='𪛟',
                '𪜀'..='𫜹',
                '𫝀'..='𫠝',
                '𫠠'..='𬺡',
                '𬺰'..='𮯠',
                '𮯰'..='𮹝',
                '丽'..='𪘀',
                '𰀀'..='𱍊',
                '𱍐'..='𲎯',
                '\u{e0100}'..='\u{e01ef}',
            ],
            &[
                'A'..='G',
                'I'..='V',
                'X'..='Z',
                '_'..='_',
                'a'..='a',
                'c'..='c',
                'g'..='k',
                'm'..='m',
                'p'..='q',
                's'..='s',
                'u'..='z',
            ],
            &['H'..='H'],
            &['W'..='W'],
            &['\\'..='\\'],
            &['b'..='b', 'f'..='f', 'n'..='n', 't'..='t'],
            &['d'..='d'],
            &['e'..='e'],
            &['l'..='l'],
            &['o'..='o'],
            &['r'..='r'],
        ];
        for (group_idx, intervals) in GROUPED_INTERVALS.iter().enumerate() {
            if intervals
                .binary_search_by(|range| {
                    if c < *range.start() {
                        Ordering::Greater
                    } else if c > *range.end() {
                        Ordering::Less
                    } else {
                        Ordering::Equal
                    }
                })
                .is_some()
            {
                return Some(group_idx);
            }
        }
        None
    }
}
"#;
        assert_eq!(formatted_code, expected_code);
    }
}
